# Generated by Django 4.0.6 on 2023-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'product_custom_title',
            },
        ),
    ]
