# Generated by Django 4.0.6 on 2023-01-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg', models.CharField(max_length=100)),
                ('pay_method', models.CharField(max_length=100)),
                ('merchant_uid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('buyer_email', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_tel', models.CharField(max_length=100)),
                ('buyer_postcode', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iamport_payload',
            },
        ),
        migrations.CreateModel(
            name='ImportSuccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imp_uid', models.CharField(max_length=100)),
                ('merchant_uid', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iamport_success',
            },
        ),
    ]
