# Generated by Django 4.0.6 on 2023-01-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kakaouser',
            name='post_code',
            field=models.CharField(default='기본값', max_length=30),
        ),
    ]
